// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.75.0. www.xsd2code.com
//    {"NameSpace":"Relational2Rdf.DataSources.Siard","CollectionObjectType":"Array","Properties":{"AutomaticProperties":true,"PascalCaseProperty":true},"XmlAttribute":{"Enabled":true},"ClassParams":{"ClassNameEndWith":"V1"},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Relational2Rdf.DataSources.Siard.SiardV1
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
	
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="siardArchive")]
    [XmlRootAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", IsNullable=false, ElementName="siardArchive")]
    public partial class SiardArchiveV1
    {
        [XmlElement("dbname")]
        public string Dbname { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlElement("archiver")]
        public string Archiver { get; set; }
        [XmlElement("archiverContact")]
        public string ArchiverContact { get; set; }
        [XmlElement("dataOwner")]
        public string DataOwner { get; set; }
        [XmlElement("dataOriginTimespan")]
        public string DataOriginTimespan { get; set; }
        [XmlElement("producerApplication")]
        public string ProducerApplication { get; set; }
        [XmlElement(DataType="date", ElementName="archivalDate")]
        public System.DateTime ArchivalDate { get; set; }
        [XmlElement("messageDigest")]
        public string MessageDigest { get; set; }
        [XmlElement("clientMachine")]
        public string ClientMachine { get; set; }
        [XmlElement("databaseProduct")]
        public string DatabaseProduct { get; set; }
        [XmlElement("connection")]
        public string Connection { get; set; }
        [XmlElement("databaseUser")]
        public string DatabaseUser { get; set; }
        [XmlArrayItemAttribute("schema", IsNullable=false)]
        public SchemaTypeV1[] schemas { get; set; }
        [XmlArrayItemAttribute("user", IsNullable=false)]
        public UserTypeV1[] users { get; set; }
        [XmlArrayItemAttribute("role", IsNullable=false)]
        public RoleTypeV1[] roles { get; set; }
        [XmlArrayItemAttribute("privilege", IsNullable=false)]
        public PrivilegeTypeV1[] privileges { get; set; }
        [XmlAttribute(AttributeName="version")]
        public VersionTypeV1 Version { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="SchemaType")]
    [XmlRootAttribute("schemaType", ElementName="SchemaType")]
    public partial class SchemaTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("folder")]
        public string Folder { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlArrayItemAttribute("table", IsNullable=false)]
        public TableTypeV1[] tables { get; set; }
        [XmlArrayItemAttribute("view", IsNullable=false)]
        public ViewTypeV1[] views { get; set; }
        [XmlArrayItemAttribute("routine", IsNullable=false)]
        public RoutineTypeV1[] routines { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="TableType")]
    [XmlRootAttribute("tableType", ElementName="TableType")]
    public partial class TableTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("folder")]
        public string Folder { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlArrayItemAttribute("column", IsNullable=false)]
        public ColumnTypeV1[] columns { get; set; }
        [XmlElement("primaryKey")]
        public PrimaryKeyTypeV1 PrimaryKey { get; set; }
        [XmlArrayItemAttribute("foreignKey", IsNullable=false)]
        public ForeignKeyTypeV1[] foreignKeys { get; set; }
        [XmlArrayItemAttribute("candidateKey", IsNullable=false)]
        public CandidateKeyTypeV1[] candidateKeys { get; set; }
        [XmlArrayItemAttribute("checkConstraint", IsNullable=false)]
        public CheckConstraintTypeV1[] checkConstraints { get; set; }
        [XmlArrayItemAttribute("trigger", IsNullable=false)]
        public TriggerTypeV1[] triggers { get; set; }
        [XmlElement(DataType="integer", ElementName="rows")]
        public string Rows { get; set; }
        
        public TableTypeV1()
        {
            PrimaryKey = new PrimaryKeyTypeV1();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="ColumnType")]
    [XmlRootAttribute("columnType", ElementName="ColumnType")]
    public partial class ColumnTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("folder")]
        public string Folder { get; set; }
        [XmlElement("type")]
        public string Type { get; set; }
        [XmlElement("typeOriginal")]
        public string TypeOriginal { get; set; }
        [XmlElement("defaultValue")]
        public string DefaultValue { get; set; }
        [XmlElement("nullable")]
        public bool Nullable { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="PrivilegeType")]
    [XmlRootAttribute("privilegeType", ElementName="PrivilegeType")]
    public partial class PrivilegeTypeV1
    {
        [XmlElement("type")]
        public string Type { get; set; }
        [XmlElement("object")]
        public string Object { get; set; }
        [XmlElement("grantor")]
        public string Grantor { get; set; }
        [XmlElement("grantee")]
        public string Grantee { get; set; }
        [XmlElement("option")]
        public PrivOptionTypeV1 Option { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="privOptionType")]
    [XmlRootAttribute("privOptionType")]
    public enum PrivOptionTypeV1
    {
        ADMIN,
        GRANT,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="RoleType")]
    [XmlRootAttribute("roleType", ElementName="RoleType")]
    public partial class RoleTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("admin")]
        public string Admin { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="UserType")]
    [XmlRootAttribute("userType", ElementName="UserType")]
    public partial class UserTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="ParameterType")]
    [XmlRootAttribute("parameterType", ElementName="ParameterType")]
    public partial class ParameterTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("mode")]
        public string Mode { get; set; }
        [XmlElement("type")]
        public string Type { get; set; }
        [XmlElement("typeOriginal")]
        public string TypeOriginal { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="RoutineType")]
    [XmlRootAttribute("routineType", ElementName="RoutineType")]
    public partial class RoutineTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlElement("source")]
        public string Source { get; set; }
        [XmlElement("body")]
        public string Body { get; set; }
        [XmlElement("characteristic")]
        public string Characteristic { get; set; }
        [XmlElement("returnType")]
        public string ReturnType { get; set; }
        [XmlArrayItemAttribute("parameter", IsNullable=false)]
        public ParameterTypeV1[] parameters { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="ViewType")]
    [XmlRootAttribute("viewType", ElementName="ViewType")]
    public partial class ViewTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("query")]
        public string Query { get; set; }
        [XmlElement("queryOriginal")]
        public string QueryOriginal { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlArrayItemAttribute("column", IsNullable=false)]
        public ColumnTypeV1[] columns { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="TriggerType")]
    [XmlRootAttribute("triggerType", ElementName="TriggerType")]
    public partial class TriggerTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("actionTime")]
        public ActionTimeTypeV1 ActionTime { get; set; }
        [XmlElement("triggerEvent")]
        public string TriggerEvent { get; set; }
        [XmlElement("aliasList")]
        public string AliasList { get; set; }
        [XmlElement("triggeredAction")]
        public string TriggeredAction { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="actionTimeType")]
    [XmlRootAttribute("actionTimeType")]
    public enum ActionTimeTypeV1
	{
        BEFORE,
        AFTER,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="CheckConstraintType")]
    [XmlRootAttribute("checkConstraintType", ElementName="CheckConstraintType")]
    public partial class CheckConstraintTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("condition")]
        public string Condition { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="CandidateKeyType")]
    [XmlRootAttribute("candidateKeyType", ElementName="CandidateKeyType")]
    public partial class CandidateKeyTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlElement("column", ElementName="column")]
        public string[] Column { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="ReferenceType")]
    [XmlRootAttribute("referenceType", ElementName="ReferenceType")]
    public partial class ReferenceTypeV1
    {
        [XmlElement("column")]
        public string Column { get; set; }
        [XmlElement("referenced")]
        public string Referenced { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="ForeignKeyType")]
    [XmlRootAttribute("foreignKeyType", ElementName="ForeignKeyType")]
    public partial class ForeignKeyTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("referencedSchema")]
        public string ReferencedSchema { get; set; }
        [XmlElement("referencedTable")]
        public string ReferencedTable { get; set; }
        [XmlElement("reference", ElementName="reference")]
        public ReferenceTypeV1[] Reference { get; set; }
        [XmlElement("matchType")]
        public MatchTypeTypeV1 MatchType { get; set; }
        [XmlElement("deleteAction")]
        public string DeleteAction { get; set; }
        [XmlElement("updateAction")]
        public string UpdateAction { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="matchTypeType")]
    [XmlRootAttribute("matchTypeType")]
    public enum MatchTypeTypeV1
	  {
        FULL,
        PARTIAL,
        SIMPLE,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="PrimaryKeyType")]
    [XmlRootAttribute("primaryKeyType", ElementName="PrimaryKeyType")]
    public partial class PrimaryKeyTypeV1
    {
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlElement("column", ElementName="column")]
        public string[] Column { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "6.2.6")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", TypeName="versionType")]
    [XmlRootAttribute("versionType")]
    public enum VersionTypeV1
	{
        [XmlEnumAttribute("1.0")]
        Siard1_0,
    }
}
#pragma warning restore
