//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relational2Rdf.DataSources.Siard.SqlMapping {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mappings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mappings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Relational2Rdf.DataSources.Siard.SqlMapping.Mappings", typeof(Mappings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string BIGINT {
            get {
                return ResourceManager.GetString("BIGINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob.
        /// </summary>
        internal static string BINARY_LARGE_OBJECT {
            get {
                return ResourceManager.GetString("BINARY LARGE OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob.
        /// </summary>
        internal static string BINARY_VARYING {
            get {
                return ResourceManager.GetString("BINARY VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string BIT {
            get {
                return ResourceManager.GetString("BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string BIT_VARYING {
            get {
                return ResourceManager.GetString("BIT VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string BOOLEAN {
            get {
                return ResourceManager.GetString("BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string CHARACTER {
            get {
                return ResourceManager.GetString("CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string CHARACTER_VARYING {
            get {
                return ResourceManager.GetString("CHARACTER VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string CHARACTER_VARYING_OBJECT {
            get {
                return ResourceManager.GetString("CHARACTER VARYING OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string DATALINK {
            get {
                return ResourceManager.GetString("DATALINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string DECIMAL {
            get {
                return ResourceManager.GetString("DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string DOUBLE_PRECISION {
            get {
                return ResourceManager.GetString("DOUBLE PRECISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string FLOAT {
            get {
                return ResourceManager.GetString("FLOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string INTEGER {
            get {
                return ResourceManager.GetString("INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpan.
        /// </summary>
        internal static string INTERVAL {
            get {
                return ResourceManager.GetString("INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NATIONAL_CHAR {
            get {
                return ResourceManager.GetString("NATIONAL CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NATIONAL_CHAR_VARYING {
            get {
                return ResourceManager.GetString("NATIONAL CHAR VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NATIONAL_CHARACTER {
            get {
                return ResourceManager.GetString("NATIONAL CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NATIONAL_CHARACTER_LARGE_OBJECT {
            get {
                return ResourceManager.GetString("NATIONAL CHARACTER LARGE OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NATIONAL_CHARACTER_VARYING {
            get {
                return ResourceManager.GetString("NATIONAL CHARACTER VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NCHAR {
            get {
                return ResourceManager.GetString("NCHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NCHAR_LARGE_OBJECT {
            get {
                return ResourceManager.GetString("NCHAR LARGE OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NCHAR_VARYING {
            get {
                return ResourceManager.GetString("NCHAR VARYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string NCLOB {
            get {
                return ResourceManager.GetString("NCLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string NUMERIC {
            get {
                return ResourceManager.GetString("NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string REAL {
            get {
                return ResourceManager.GetString("REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string SMALLINT {
            get {
                return ResourceManager.GetString("SMALLINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpan.
        /// </summary>
        internal static string TIME_WITH_TIME_ZONE {
            get {
                return ResourceManager.GetString("TIME WITH TIME ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpan.
        /// </summary>
        internal static string TIME_WITHOUT_TIME_ZONE {
            get {
                return ResourceManager.GetString("TIME WITHOUT TIME ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TIMESTAMP_WITH_TIME_ZONE {
            get {
                return ResourceManager.GetString("TIMESTAMP WITH TIME ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TIMESTAMP_WITHOUT_TIME_ZONE {
            get {
                return ResourceManager.GetString("TIMESTAMP WITHOUT TIME ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob.
        /// </summary>
        internal static string VARBINARY {
            get {
                return ResourceManager.GetString("VARBINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string VARCHAR {
            get {
                return ResourceManager.GetString("VARCHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
